plugins:
  topic_gallery_enabled:
    default: false
    client: false
  topic_gallery_allowed_groups:
    type: group_list
    list_type: compact
    default: "1" # admin group
    allow_any: false
    refresh: true
